/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  AuctionManager,
  AuctionManagerInterface,
} from "../AuctionManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract Auction",
        name: "auctionAdress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "AuctionCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract Auction",
        name: "newAuction",
        type: "address",
      },
    ],
    name: "AddAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "auctions",
    outputs: [
      {
        internalType: "contract Auction",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAuctionCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506103b18061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80631f4f7b2614610046578063571a26a014610062578063c44e664014610092575b600080fd5b610060600480360381019061005b919061020f565b6100b0565b005b61007c60048036038101906100779190610272565b61014f565b60405161008991906102fe565b60405180910390f35b61009a61018e565b6040516100a79190610328565b60405180910390f35b6000819080600181540180825580915050600190039060005260206000200160009091909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055507f0bdb7849ed0b0249d0f995067a2ca77769f68ab4c654931e262676effeb395f28133604051610144929190610352565b60405180910390a150565b6000818154811061015f57600080fd5b906000526020600020016000915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60008080549050905090565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101ca8261019f565b9050919050565b60006101dc826101bf565b9050919050565b6101ec816101d1565b81146101f757600080fd5b50565b600081359050610209816101e3565b92915050565b6000602082840312156102255761022461019a565b5b6000610233848285016101fa565b91505092915050565b6000819050919050565b61024f8161023c565b811461025a57600080fd5b50565b60008135905061026c81610246565b92915050565b6000602082840312156102885761028761019a565b5b60006102968482850161025d565b91505092915050565b6000819050919050565b60006102c46102bf6102ba8461019f565b61029f565b61019f565b9050919050565b60006102d6826102a9565b9050919050565b60006102e8826102cb565b9050919050565b6102f8816102dd565b82525050565b600060208201905061031360008301846102ef565b92915050565b6103228161023c565b82525050565b600060208201905061033d6000830184610319565b92915050565b61034c816101bf565b82525050565b600060408201905061036760008301856102ef565b6103746020830184610343565b939250505056fea264697066735822122091d98c43acd4499dfad9bda1d9250e9ff6c6fc950b6689d179f4c0fa0e0c675f64736f6c634300081c0033";

type AuctionManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuctionManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuctionManager__factory extends ContractFactory {
  constructor(...args: AuctionManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuctionManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuctionManager__factory {
    return super.connect(runner) as AuctionManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuctionManagerInterface {
    return new Interface(_abi) as AuctionManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuctionManager {
    return new Contract(address, _abi, runner) as unknown as AuctionManager;
  }
}
